// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type List struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description *string     `json:"description,omitempty"`
	Entries     []*Question `json:"entries"`
}

type Mutation struct {
}

type NewList struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type NewQuestion struct {
	Title      string `json:"title"`
	URL        string `json:"url"`
	Difficulty string `json:"difficulty"`
}

type Query struct {
}

type Question struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	URL        string `json:"url"`
	Difficulty string `json:"difficulty"`
	Complete   bool   `json:"complete"`
}

type UpdateList struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UpdateQuestion struct {
	Title      *string `json:"title,omitempty"`
	URL        *string `json:"url,omitempty"`
	Difficulty *string `json:"difficulty,omitempty"`
}
